# .travis.yml
#
# YAML configuration file for the continuous integration platform "Travis CI".
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://gnu.org/licenses/lgpl.txt>.
#
# Author:    Florian Wolters <wolters.fl@gmail.com>
# Copyright: 2012-2014 Florian Wolters
# License:   http://gnu.org/licenses/lgpl.txt LGPL-3.0+
# Link:      http://github.com/FlorianWolters/PHP-Component-Core-Immutable

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer selfupdate
  - composer install --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - php vendor/bin/phpunit --coverage-text -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover review/phpcov/coverage.xml

notifications:
  email:
    on_success: change
    on_failure: always
